name: Build and Deploy JESD Eye Scan GTK

env:
  MAINTAINER: "Nicu Siderias <nicu.siderias@analog.com>"
  MAJOR: 0 
  MINOR: 0
  PATCH: ${{ github.sha }}
  SOURCE_CODE: jesd-eye-scan-gtk-source
  EXECUTABLE_LOCATION: usr/local/bin
  SHARE_LOCATIONS: usr/local/share/jesd
  BUILD_FOLDER: build

on:
  push:
    branches: 
      - main
      - '20[1-9][0-9]_R[1-9]'
  pull_request:
    branches:
      - main
      - '20[1-9][0-9]_R[1-9]' 

jobs:
  build_and_deploy:
    defaults:
      run:
        working-directory: ${{env.SOURCE_CODE}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - container: aandrisa/kuiper_basic_64:latest
          - container: aandrisa/kuiper_basic_32:latest
    container: ${{ matrix.container }}
    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4
      with: 
        path: ${{env.SOURCE_CODE}}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake gnuplot libgtk-3-dev libncurses-dev

    - name: Build code with Cmake 
      run: |
        mkdir ${{env.BUILD_FOLDER}}
        cd ${{env.BUILD_FOLDER}}
        cmake -DENABLE_PACKAGING=ON -DMAINTAINER="${{env.MAINTAINER}}" -DPROJECT_VERSION="${{env.MAJOR}}.${{env.MINOR}}.${{env.PATCH}}" ..
    
    - name: Install application
      run: |
        cd ${{env.BUILD_FOLDER}}
        sudo make install
        
    - name: Verify install locations 
      run: |
        [ -e "/${{env.EXECUTABLE_LOCATION}}/jesd_status" ] \
        && [ -e "/${{env.EXECUTABLE_LOCATION}}/jesd_eye_scan" ] \
        && [ -e "/${{env.EXECUTABLE_LOCATION}}/jesd_eye_scan_autostart.sh" ] \
        && [ -e "/${{env.SHARE_LOCATIONS}}/jesd.glade" ] \
        && [ -e "/${{env.SHARE_LOCATIONS}}/ADIlogo.png" ] \
        && sudo [ -e "/root/.config/autostart/jesd_eye_scan.desktop" ] \
        && echo "Installation successful" \
        || { echo "Installation failed, some files are missing"; exit 1; }

    - name: Create .deb package artifact
      run: |
        cd ${{env.BUILD_FOLDER}}
        make package

    - name: Upload .deb artifacts to github
      uses: actions/upload-artifact@v4
      with:
        name: jesd-eye-scan-gtk
        path: ${{env.SOURCE_CODE}}/${{env.BUILD_FOLDER}}/jesd-eye-scan-gtk_${{env.MAJOR}}.${{env.MINOR}}.0+${{env.PATCH}}_${{env.ARCHITECTURE}}.deb
        if-no-files-found: error
