name: Build and Deploy JESD Eye Scan GTK

env:
  MAINTAINER: "Nicu Siderias <nicu.siderias@analog.com>"
  MAJOR: 0 
  MINOR: 0
  PATCH: ${{ github.sha }}
  ARCHITECTURE: all
  SOURCE_CODE: jesd-eye-scan-gtk-source
  EXECUTABLE_LOCATION: usr/local/bin
  SHARE_LOCATIONS: usr/local/share/jesd

on:
  push:
    branches: 
      - main
      - '20[1-9][0-9]_R[1-9]'
  pull_request:
    branches:
      - main
      - '20[1-9][0-9]_R[1-9]' 

jobs:
  build_and_deploy:
    defaults:
      run:
        working-directory: ${{env.SOURCE_CODE}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4
      with: 
        path: ${{env.SOURCE_CODE}}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gnuplot libgtk-3-dev libncurses-dev

    - name: Build C code
      run: make all
    
    - name: Install application
      run: |
        sudo make install

        [ -e "/${{env.EXECUTABLE_LOCATION}}/jesd_status" ] \
        && [ -e "/${{env.EXECUTABLE_LOCATION}}/jesd_eye_scan" ] \
        && [ -e "/${{env.EXECUTABLE_LOCATION}}/jesd_eye_scan_autostart.sh" ] \
        && [ -e "/${{env.SHARE_LOCATIONS}}/jesd.glade" ] \
        && [ -e "/${{env.SHARE_LOCATIONS}}/ADIlogo.png" ] \
        && sudo [ -e "/root/.config/autostart/jesd_eye_scan.desktop" ] \
        && echo "Installation successful" \
        || { echo "Installation failed, some files are missing"; exit 1; }

    - name: Create artifact directory
      run: |
        mkdir -p artifacts/DEBIAN
        mkdir -p artifacts/${{env.EXECUTABLE_LOCATION}}
        mkdir -p artifacts/${{env.SHARE_LOCATIONS}}
        mkdir -p artifacts/root/.config/autostart/
        cp jesd_eye_scan artifacts/${{env.EXECUTABLE_LOCATION}}
        cp jesd_status artifacts/${{env.EXECUTABLE_LOCATION}}
        cp jesd_eye_scan_autostart.sh artifacts/${{env.EXECUTABLE_LOCATION}}
        cp jesd.glade artifacts/${{env.SHARE_LOCATIONS}}/
        cp icons/ADIlogo.png artifacts/${{env.SHARE_LOCATIONS}}/
        cp jesd_eye_scan.desktop ./artifacts/root/.config/autostart/jesd_eye_scan.desktop
        echo -e "Package: jesd-eye-scan-gtk\nVersion: ${MAJOR}.${MINOR}.${PATCH}\nMaintainer: ${MAINTAINER}\nArchitecture: ${ARCHITECTURE}\nDescription: Eye Scan Visualization Utility" > ./artifacts/DEBIAN/control
        dpkg-deb --build artifacts/ .

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v4
      with:
        name: jesd-eye-scan-gtk
        path: ${{env.SOURCE_CODE}}/jesd-eye-scan-gtk_${{env.MAJOR}}.${{env.MINOR}}.${{env.PATCH}}_${{env.ARCHITECTURE}}.deb
        if-no-files-found: error
